apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-server-guestbook-app
spec:
  destination:
    name: minikube
    namespace: test
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/sathish369369/demoargocd.git
    targetRevision: master
  syncPolicy:
    automated: {}
